name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main
env:
  ECR_REPOSITORY: notes-app
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Set up Environment Variables
      run: |
        echo "${{secrets.envFile}}" > .env

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Build and Push Docker Image to ECR
      run: |
        docker build -t ${{ secrets.AWS_ECR_REGISTRY_URI }}/your-repository-name:latest .
        docker login -u AWS -p ${{ secrets.AWS_REGISTRY_TOKEN }} ${{ secrets.AWS_ECR_REGISTRY_URI }}
        docker push ${{ secrets.AWS_ECR_REGISTRY_URI }}/your-repository-name:latest
